"""add seller_id to products

Revision ID: 5d4fcbe9cfb9
Revises: cd3ba6367cba
Create Date: 2026-02-15 23:37:21.617598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4fcbe9cfb9'
down_revision: Union[str, Sequence[str], None] = 'cd3ba6367cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'seller_id')
    # ### end Alembic commands ###
