"""add owner_id to shops

Revision ID: eaada90ebed0
Revises: 5d4fcbe9cfb9
Create Date: 2026-02-16 04:02:12.102063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaada90ebed0'
down_revision: Union[str, Sequence[str], None] = '5d4fcbe9cfb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shops', 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_column('shops', 'owner_id')
    # ### end Alembic commands ###
